engines:
  bandit:
    enabled: true
  duplication:
    config:
      languages:
      - python
    enabled: true
  pylint:
    enabled: true
  radon:
    enabled: true
exclude_paths:
- bin
- build
- dist
- htmlcov
- tests
- venv
